### ISSUE TITLE
web3.js: replace dependencies to lower supply-chain risk, improve tree-shakeability, and reduce bundle size

### ISSUE THREAD

**Issue by paulmillr** [solana-labs/solana-web3.js#1103]
You have quite a few dependencies in web3. All of those can be replaced by 4 deps:

```
"@ethersproject/sha2": "^5.5.0",
"bigint-buffer": "^1.1.5",
"bn.js": "^5.0.0",
"bs58": "^4.0.1",
"buffer": "6.0.1",
"js-sha3": "^0.8.0",
"secp256k1": "^4.0.2",
"tweetnacl": "^1.0.0"
```

I suggest switching to [audited libraries](https://paulmillr.com/noble/) that are faster, use less dependencies.

- `@noble/hashes` for sha2, sha3. It's faster than ethersproject/sha2, js-sha3, and was audited
- `@noble/secp256k1` for secp256k1. It's faster than js implementations of secp, and was audited
- `@noble/ed25519` for ed25519 — which is 7x faster than tweetnacl, and was audited
- `@scure/base` could be used for `base58` — it was audited and has 0 deps
- `bn.js`, `bigint-buffer`, `buffer` can be removed altogether

Supply chain attacks are very dangerous. Breaking any sub-dependency of your dependencies could leak user keys. So, the best option is to use projects that don't have sub-dependencies.

---
Individual tracking tasks

- [x] solana-labs/solana#26933
- [x] solana-labs/solana#27390
- [ ] solana-labs/solana-web3.js#1100
- [x] solana-labs/solana-web3.js#1101
- [x] solana-labs/solana#27629

**Comment by paulmillr** [comment]
@steveluscher heads up, much smaller v2 of noble-secp, noble-ed is out. Many features have been removed, but should be fine for your case. The libraries are just 4kb gzipped now.

Another option is to use noble-curves which have improved security, are larger; but tree shaking is supported so all is cool.

**Comment by steveluscher** [comment]
Thanks, @paulmillr!

**Comment by steveluscher** [comment]
Closed by 5a20ed0649fd0fa28d4b6a96ba042c9cdb47630e.
